server:
  port: 8009
spring:
  datasource:
    url: jdbc:mysql://192.168.2.246:3306/capsys-basic?noAccessToProcedureBodies=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 30000
    password:
    jedis:
      pool:
        max-idle: 6
        max-wait: 5000
        max-active: -1
        min-idle: 3
#加入dao，mapper 扫描
mybatis:
  typeAliasesPackage: com.example.demo.modular.entity
  mapperLocations: classpath:mapper/*.xml
